version: '3'
services:
    node_alice:
        image: nodle/chain
        user: nodle-chain:nodle-chain
        ports:
            - "30344:30344"
            - "44190:44190"
        volumes:
            - "polkadot-data-alice:/alice"
        command: --chain=local --base-path=/alice --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --port 30344 --ws-port 44190 --rpc-cors all --pruning archive --alice --node-key 721ad2a40449e78581c787b2cff1c3fb2148e0e6b7e083addc6c7634f55aa83e
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

volumes:
    polkadot-data-alice:
    polkadot-data-bob:
    polkadot-data-novnv-01:
    polkadot-data-novnv-02:
    polkadot-data-novnv-03:
    polkadot-data-novnv-04:
    polkadot-data-novnv-05:
    polkadot-data-novnv-06:
    polkadot-data-novnv-07:
    polkadot-data-novnv-08:
    polkadot-data-novnv-09:
    polkadot-data-novnv-10:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
