apiVersion: skaffold/v2beta23
kind: Config

profiles:
  - name: minikube-staking-local
    deploy:
      kubectl:
        manifests:
          - kubes/node-staking-local-alice-deployment.yml
          - kubes/node-staking-local-alice-service.yml
          - kubes/node-staking-local-bob-deployment.yml
          - kubes/node-staking-local-bob-service.yml
  - name: minikube-main-local
    deploy:
      kubectl:
        manifests:
          - kubes/node-main-local-alice-deployment.yml
          - kubes/node-main-local-alice-service.yml
          - kubes/node-main-local-bob-deployment.yml
          - kubes/node-main-local-bob-service.yml
