apiVersion: v1
kind: Service
metadata:
  name: nodle-chain-bob
  labels:
    app: nodle-chain-bob
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - name: chain-ws
      port: 9944
      targetPort: chain-ws
    - name: chain-metric
      port: 9615
      targetPort: chain-metric
  selector:
    app: nodle-chain-bob
